FROM python:3.11-slim

WORKDIR /app

COPY . .

RUN pip install fastapi uvicorn sqlalchemy pydantic
COPY . .

ENV PYTHONPATH=/app
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8002"]
