apiVersion: apps/v1
kind: Deployment
metadata:
  name: property-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: property-service
  template:
    metadata:
      labels:
        app: property-service
    spec:
      containers:
      - name: property-service
        image: 314146315010.dkr.ecr.us-east-1.amazonaws.com/property-service:latest
        ports:
        - containerPort: 8002
---
apiVersion: v1
kind: Service
metadata:
  name: property-service
spec:
  type: LoadBalancer
  selector:
    app: property-service
  ports:
  - port: 8002
    targetPort: 8002
