apiVersion: apps/v1
kind: Deployment
metadata:
  name: attendance-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: attendance-service
  template:
    metadata:
      labels:
        app: attendance-service
    spec:
      containers:
      - name: attendance-service
        image: 314146315010.dkr.ecr.us-east-1.amazonaws.com/attendance-service:latest
        ports:
        - containerPort: 8003
---
apiVersion: v1
kind: Service
metadata:
  name: attendance-service
spec:
  type: LoadBalancer
  selector:
    app: attendance-service
  ports:
  - port: 8003
    targetPort: 8003
