FROM python:3.9-slim

WORKDIR /app

COPY . .

RUN pip install fastapi uvicorn sqlalchemy bcrypt python-jose[cryptography] pydantic passlib pydantic[email]

COPY . .

ENV PYTHONPATH=/app

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8001"]
