apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: task-service
  template:
    metadata:
      labels:
        app: task-service
    spec:
      containers:
      - name: task-service
        image: 314146315010.dkr.ecr.us-east-1.amazonaws.com/task-service:latest
        ports:
        - containerPort: 8004
---
apiVersion: v1
kind: Service
metadata:
  name: task-service
spec:
  type: LoadBalancer
  selector:
    app: task-service
  ports:
  - port: 8004
    targetPort: 8004
